function simpleCnn(nclasses)
   local net = nn.Sequential()
   net:add(nn.SpatialConvolution(3,32,5,5))
   net:add(nn.ReLU(true))
   net:add(nn.SpatialMaxPooling(2,2,2,2))
   net:add(nn.SpatialBatchNormalization(32))
   net:add(nn.SpatialConvolution(32,64,5,5))
   net:add(nn.ReLU(true))
   net:add(nn.SpatialMaxPooling(2,2,2,2))
   net:add(nn.SpatialBatchNormalization(64))
   net:add(nn.SpatialConvolution(64,128,5,5))
   net:add(nn.ReLU(true))
   net:add(nn.SpatialBatchNormalization(128))
   net:add(nn.View(-1,128*18*18))
   net:add(nn.Dropout(0.5))
   net:add(nn.Linear(128*18*18,1024))
   net:add(nn.ReLU(true))
   net:add(nn.BatchNormalization(1024))
   net:add(nn.Dropout(0.5))
   net:add(nn.Linear(1024,nclasses))
   return net
end
